blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('blog/', views.blog, name="blog"),
    path('search/', views.search_results, name="search_results"),
    path('post/<str:slug>', views.post_detail, name="post_detail_url"),
    path('category/<slug:slug>/', views.category_detail, name="category_detail_url"),
    path('categories/', views.Categories_detail, name="categories_detail_url"),
    path('register/', views.register, name="register"),
    path('post/<slug:slug>/leave-comment', views.leave_comment, name='leave_comment'),
    path('contact/', views.contact, name="contact"),
    path('populars/', views.populars, name="populars"),
]

djangosite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.shortcuts import reverse

class Category(models.Model):
    title = models.CharField('Заголовок', max_length=255 )
    slug = models.SlugField('Ссылка', max_length=255, unique=True)
    image = models.ImageField('Картинка', blank=True)
    

    def get_absolute_url(self):
        return reverse('category_detail_url', kwargs={'slug':self.slug})
        
    class Meta:
        verbose_name="Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.title





class Post(models.Model):
    title = models.CharField('Загаловок', max_length=255 )
    slug = models.SlugField('Сcылка', max_length=255, unique=True)
    summary = models.TextField('Краткое Описание')
    content = models.TextField('Описаниe')
    date = models.DateTimeField('Дата', default = timezone.now)
    image = models.ImageField('Картинка', blank=True)
    categories = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    views = models.IntegerField('Просмотры', default=0)



    def get_absolute_url(self):
        return reverse('post_detail_url', kwargs={'slug':self.slug})

    class Meta:
        verbose_name="Пост"
        verbose_name_plural="Посты"

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author_name = models.CharField("Имя Автора", max_length=255)
    text = models.TextField("Текст Коментарии")
    date = models.DateTimeField("Дата коментария", default=timezone.now)

    class Meta:
        verbose_name = "Коментарий"
        verbose_name_plural = "Коментраии"

    def __str__(self):
        return self.author_name

class FeedBack(models.Model):
    name = models.CharField("Имя", max_length=255)
    last_name = models.CharField("Фамилия", max_length=255)
    email = models.EmailField("Ваш эмайл")
    phone = models.CharField("Телефон номера", max_length=255)
    message = models.TextField("Сообщение")
    date = models.DateTimeField("Дата", default=timezone.now)

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"

    def __str__(self):
            return self.name

        

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(label="Никнейм", required=True, widget=forms.TextInput(attrs={'class' : 'form-control footer-input margin-b-20'}))
    password1 = forms.CharField(label="Пароль", required=True, widget=forms.PasswordInput(attrs={'class' : 'form-control footer-input margin-b-20'}))
    password2 = forms.CharField(label="Повторите Пароль", required=True, widget=forms.PasswordInput(attrs={'class' : 'form-control footer-input margin-b-20'}))
    email = forms.EmailField(label="Эмайл", required=True, widget=forms.TextInput(attrs={'class' : 'form-control footer-input margin-b-20'}))
    first_name = forms.CharField(label="Имя", required=True, widget=forms.TextInput(attrs={'class' : 'form-control footer-input margin-b-20'}))
    last_name = forms.CharField(label="Фамилия", required=True, widget=forms.TextInput(attrs={'class' : 'form-control footer-input margin-b-20'}))

    class Meta:
        model = User
        fields = ("first_name", "last_name", "email", "password1", "password2", "username")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.save()
        return user
        

blog/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from .models import Category, Post, FeedBack
from .forms import RegisterForm
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.models import User
def index(request):
    news = Post.objects.order_by('-date')[:3]
    context = {'news':news}
    return render(request, 'blog/index.html', context)

def populars(request):
    popular = Post.objects.filter(views__gt=10)[:3]
    return render(request, 'blog/popular_post.html', {'popular':popular})


def blog(request):
    news = Post.objects.order_by('-date')[:3]
    return render(request, 'blog/news.html', {'news':news})
    
def search_results(request):
    query = request.GET.get('search')
    search_obj = Post.objects.filter(Q(title__icontains = query) | Q(summary__icontains = query))
    return render(request, 'blog/search_result.html', {'query':query, 'search_obj':search_obj})

def post_detail(request, slug):
    post = Post.objects.get(slug__iexact = slug)
    post.views += 1
    post.save()
    return render(request, 'blog/post_detail.html', {'post':post})

def category_detail(request, slug):
    category = Category.objects.get(slug__iexact = slug)
    posts = Post.objects.order_by('-date')
    return render(request, 'blog/category_detail.html', {'category':category, 'posts':posts})

def Categories_detail(request):
    categories = Category.objects.all()
    return render(request, 'blog/Categories.html', {'categories':categories})

def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = RegisterForm()
    return render(request, 'blog/register.html', {'form':form})

def logout(request):
    logout(request)
    return redirect('index')

def leave_comment(request, slug):
    post = Post.objects.get(slug__iexact=slug)
    if request.user.is_authenticated:
        user = request.user.first_name
        post.comment_set.create(
            author_name = user,
            text = request.POST.get('text')
        )
    else:
        post.comment_set.create(
            author_name = request.POST.get('name'),
            text = request.POST.get('text')
        )
    return HttpResponseRedirect(reverse('post_detail_url', args = (post.slug,)))

def contact(request):
    if request.method == "POST":
        if request.user.is_authenticated:
            first_name = request.user.first_name
            last_name = request.user.last_name
            email = request.user.email
            FeedBack.objects.create(
                name = first_name,
                last_name = last_name,
                email = email,
                phone = request.POST.get('phone'),
                message = request.POST.get('message')
            )
        else:
            FeedBack.objects.create(name = request.POST.get('name'), 
            last_name = request.POST.get("last_name"),
            email = request.POST.get("email"),
            phone = request.POST.get("phone"),
            message = request.POST.get("message")
        )
    return render(request, 'blog/contact.html')

blog/templates/blog/Categories.html
{% extends 'blog/base.html' %}
{% block title%}
{{post.title}}
{% endblock %}
{% block content%}

<section class="content">
    <div class="row">
        {% for category in categories %}
        <div>
            <a href="{{category.get_absolute_url}}"><h2 style="text-align: center;">{{category.title}}</h2>
            {% if category.image.url != null %}
            <img style="text-align: center; width: 100%;" src="{{category.image.url}}" alt="">
            {% endif %}
            </a>
        </div>
        {% endfor %}
    </div>
</section>
{% endblock%}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        helo werld
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>



  <!--Nav-Bar-->
  <div class="pos-f-t">
    <div class="collapse" id="navbarToggleExternalContent">
      <div class="bg-dark p-4">
        <h4 class="text-white">Обо мне</h4>
        <span class="text-muted">
          <br>
          <br>
          <br>
        </span>
      </div>
    </div>
    <nav class="navbar navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="spinner-border text-warning" role="status">
        <span class="sr-only">Loading...</span>
      </div>
      <a href="{% url 'register' %}"><button type="button" class="btn btn-outline-success">Регистрись Плять</button></a>
      <a href="{% url 'login' %}" type="button" class="btn btn-outline-danger">Вход</a>
      <a href="{% url 'contact' %}" type="button" class="btn btn-outline-warning">Взаимо-Связь</a>
      <nav class="navbar navbar-light bg-light">
        <form class="form-inline" action="{% url 'search_results' %}" method="GET">
          <input class="form-control mr-sm-2" type="search" placeholder="Поиск" name="search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </nav>
    </nav>
  </div>
  <!--End Nav-Bar-->
        {% block content %}
        {% endblock %}
    <footer></footer >
        
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

blog/templates/blog/category_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %}
    Главная
{% endblock %}

{% block content%}
<div class="container-fluid">
    <div class="row">
  
  
    {% for post in category.post_set.all %}
      <div class="col-md-3">
        <a href="{{post.categories.get_absolute_url}}">
          <p>{{post.categories.title}}</p>
        </a>
          <a href="{{post.get_absolute_url}}">
            <h3>{{post.title}}</h3>
          </a>
          {% if post.image.url != null%}
          <a href="{{post.get_absolute_url}}">
           <img src="{{post.image.url}}" style="width: 100%;">
          </a>
          {% endif %}
          <p>{{post.summary}}</p>
          <em>{{post.date}}</em>
      </div>
    {% endfor %}
  
  
    </div>
  </div> 
  {% endblock %}

blog/templates/blog/contact.html
{% extends 'blog/base.html' %}

{% block title %}
Обратная связь
{% endblock %}

{% block content %}
<section class="container">
    <h1>Обратитесь не стесьняя!</h1>
    <div class="row">
        <form action="{% url 'contact' %}" method="POST">
            {% csrf_token %}
            {% if not user.is_authenticated %}
                    <label>Имя</label>
                    <input type="text" class="form-control" name="name">
                    <p>
                    <label>Фамилия</label>
                    <input type="text" class="form-control" name="last_name">
                    </p>
                    <p>
                    <label>Ваш E-Mail</label>
                    <input type="email" class="form-control" name="email">
                    </p>
            {% endif %}
                    <p>
                    <label>Телефон</label>
                    <input type="text" class="form-control" name="phone">
                    </p>
                    <label>Сообщение</label>
                    <textarea name="message" cols="30" rows="10" class="form-control"></textarea>
                    <button class="btn btn-outline-danger">Отправить</button>
        </form>
    </div>
</section>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title%}
    Главная
{% endblock %}

{% block content %}

<div class="container-fluid">
  </div>
  <div class="row">
  {% for post in news%}
    <div class="col-md-3">
      <a href="{{post.get_absolute_url}}">
        <h3>{{post.title}}</h3>
      </a>
        {% if post.image.url != null %}
          <img src="{{post.image.url}}" alt="" width="100%">
        {% endif %}
          <p>{{post.summary}}</p>
        <em>{{post.date|date:"h:s d Y "}}</em>
    </div>
  {% endfor %}
  </div>
</div>
</div>
{% endblock %}

blog/templates/blog/news.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %}
    Главная
{% endblock %}

{% block content%}
<div class="container-fluid">
    <div class="row">
  
  
    {% for post in news %}
      <div class="col-md-3">
        <a href="{{post.categories.get_absolute_url}}">
          <p>{{post.categories.title}}</p>
        </a>
          <a href="{{post.get_absolute_url}}">
            <h3>{{post.title}}</h3>
          </a>
          {% if post.image.url != null%}
          <a href="{{post.get_absolute_url}}">
           <img src="{{post.image.url}}" style="width: 100%;">
          </a>
          {% endif %}
          <p>{{post.summary}}</p>
          <em>{{post.date}}</em>
      </div>
    {% endfor %}
  
  
    </div>
  </div> 
  {% endblock %}

blog/templates/blog/popular_post.html
{% extends 'blog/base.html' %}

{% block title %}
Популярные посты
{% endblock %}

{% block content %}
<h1>Популярные посты по просмотрам</h1>
  <div class="row">
  {% for post in popular %}
    <div class="col-md-3">
        <h3>{{post.title}}</h3>
          <img src="{{post.image.url}}" alt="" width="100%">
          <p>{{post.summary}}</p>
        <em>{{post.date|date:"h:s d Y "}}</em>
        <em>Просмотры: {{post.views}}</em>
    </div>
  {% endfor %}
  </div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block title%}
{{post.title}}
{% endblock %}
{% block content%}
{% if post.image.url != null %}
<style>
    .bg-single{
        background: url('{{post.image.url}}'), rgba(0,0,0,0.7);
        background-size: cover;
        background-blend-mode: multiply;
        height: 300px;
        text-align: center;
    }
</style>
        
    <section class="container-fluid  bg-single ">
    <h1>{{post.title}}</h1>
    <p>{{post.summary}}</p>
    </section>
        {% endif %}

<section class="content">
    <div class="row">
        <a href=""><h2 style="text-align: center;">{{post.title}}</h2>
        <img style="text-align: center; width: 100%;" src="{{post.image.url}}" alt="">
    </a>
        <p>{{post.content}}</p>
        <em>{{post.date}}</em>
    </div>
</section>
<section>
    <h3>Комментариев: {{post.comment_set.count}}</h3>
    {% for comment in post.comment_set.all %}
    <div>
        <h3>{{comment.author_name}}</h3>
        <p>{{comment.text}}</p>
        <em>{{commnet.date|date:"D j M, Y"}}</em>
    </div>
    {% endfor %}
</section>
<section class="content">
    <div class="row">
        <h3>Оставьте коментарий</h3>
        <form action="{% url 'leave_comment' post.slug %}" method="POST">
            {% csrf_token %}
            {% if not user.is_authenticated %}
            <input type="text" style="width: 100%;" class="form-control">
            {% endif %}
            <textarea name="text" class="form-control" cols="30" rows="10"></textarea>
            <button type="submit" class="btn btn-success">Send</button>
            
        </form>
    </div>

</section>
{% endblock%}

blog/templates/blog/register.html
{% extends 'blog/base.html' %}
{% block title %}
Form Registration
{% endblock %}

{% block content %}
<section class="container">
    <h1>ФОрма регистрации</h1>
    <form action="{% url 'register' %}" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-success">Зарегистрироватся</button>
    </form>
</section>
{% endblock %}

blog/templates/blog/search_result.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title%}
   Поиск по запрсу: {{query}}
{% endblock %}

{% block content%}
<div class="container-fluid">
    <div class="row">
  
  
    {% for post in search_obj %}
      <div class="col-md-3">
        {% if post.image.url != null %}
          <a href=""><h3>{{post.title}}</h3>
            <img src="{{post.image.url}}" alt="" width="100%"></a>
          {% endif %}
            <p>{{post.summary}}</p>
          <em>{{post.date}}</em>
      </div>
    {% endfor %}
    </div>
  </div> 
  {% endblock %}